### ISSUE TITLE
Grant management rights based on PMPro level

### ISSUE THREAD

**Issue by dadap** [dadap/chabal-tetlh#15]

**Comment by qurgh** [comment]
"KLI Officer" level should have the ability to lock words. Delete should be limited to site admins only, but should only Trash the suggestion, hiding it from the public view.

**Comment by dadap** [comment]
This was actually implemented with commit 7203712 but I accidentally cited the wrong issue in the commit message for that commit. There's a new setting in the plugin settings to specify PMPro levels that can manage the entries.

For delete, I can change it so users can't delete their own words, and site admins can trash the words (but I guess leave them around to be untrashed if need be later?) Since I didn't actually close this issue when I intended to, I can leave it open to track that, instead.

**Comment by dadap** [comment]
As of 57a9d6d5 only admins can remove words, and they get trashed instead of actually deleted.
