### ISSUE TITLE
Allow different vote weights for different classes of user

### ISSUE THREAD

**Issue by dadap** [dadap/chabal-tetlh#8]

**Comment by qurgh** [comment]
Add a way to flag users as having a "class" based on KLCP level passed. This would "boost" the weight of their votes to higher than the level of a guest or KLI Member. 

I also wonder if guests should have a negative to their votes weights, so they have less of an impact.

**Comment by dadap** [comment]
So I was thinking about this and I do think that something should be done to differentiate votes at the top of the pack a bit more. I worry that if some words are so universally popular that everybody upvotes them, we could end up with a cluster of top words with a very small point spread, and that cluster could be as large as or even larger than the number of “top” entries to get selected.

Perhaps if we tie the idea of different vote weights with a more graduated system where a vote isn’t a simple up/down but rather a number in a range, that will allow voters to be more nuanced with their votes. For example, if the base weight for a non-paying member with no KLCP level is 1, and you get an additional 1 weight for being a paying member, and an additional 1 x KLCP level for having passed KLCP, then:

Guest member, no KLCP: can vote from -1 to +1
Paying member, no KLCP: can vote from -2 to +2
Guest member, KLCP2: can vote from -3 to +3
Paying member, KLCP3: can vote from -5 to +5

Then the people with more points might make decisions like, “hey, I like this word, but maybe at only a +2, while I like this other word at a +4”

How does that sound?

**Comment by dadap** [comment]
There's support for this now. I don't think the KLCP part is actually implemented, and it's only based on member type, but adding KLCP support requires tracking KLCP level on the KLI site itself at this point. Closing.
