### ISSUE TITLE
Add category tags

### ISSUE THREAD

**Issue by dadap** [dadap/chabal-tetlh#9]

**Comment by qurgh** [comment]
Added a custom taxonomy called {muz_Segh}
Added category dropdown to word submit form

We'll need to come up with a list of mu' Seghmey to add before list goes live

**Comment by dadap** [comment]
Cool, let's not forget to add the mu' Seghmey to the Javascript that renders the list, either.

**Comment by dadap** [comment]
This was resolved a while ago, I think. Reopen if I'm wrong.
